PRESET_BASE: mainnet
CONFIG_NAME: l1

GENESIS_FORK_VERSION: 0x20000089

ALTAIR_FORK_EPOCH: 0
ALTAIR_FORK_VERSION: 0x20000090

BELLATRIX_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x20000091

CAPELLA_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x20000092

DENEB_FORK_VERSION: 0x20000093
DENEB_FORK_EPOCH: 0

ELECTRA_FORK_EPOCH: 10000000
ELECTRA_FORK_VERSION: 0x20000094

# SECONDS_PER_SLOT: 3
# SLOTS_PER_EPOCH: 2

TERMINAL_TOTAL_DIFFICULTY: 0
MAX_WITHDRAWALS_PER_PAYLOAD: 16

DEPOSIT_CHAIN_ID: 25371
DEPOSIT_NETWORK_ID: 25371
DEPOSIT_CONTRACT_ADDRESS: 0x2d2d2d62322d6875622d65786563746f722d2d2d

MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 50
